### ISSUE TITLE
Update release spike

### ISSUE THREAD

**Issue by D4nte** [comit-network/spikes#30]
_Issue created so I don't forget_

- [x] Soft Yes on releasing on UX changes
- [x] title not needed in Recommendation Summary
- [x] COMIT API change includes protocol change
    - [x] Need to look at p2p versioning: ~#1220~ https://github.com/comit-network/spikes/commit/802834a41b576c71b892b7df14ef2f8b9c3c6310
- [x] Btsieve API Changes: Yes release btsieve
- [x] Keep same version number for cnd and btsieve (status quo regarding handling of btsieve API breaking changes). same git tag is used.
- [x] Create issue for version check of btsieve, needs to be the same than cnd #1219
- [x] Franck to open "Come up with a common contract validations strategy to ensure compatibility between cnd and its clients" issue -> make optional for releasing comit-network/comit-rs#1221
- [x] No testnet validation
- [x] Add to release actions: PR to increase version in Cargo.tomls and changelog
- [x] Git flow : branching strategy
- [x] Merge PR that triggers a release? -> Create issue to release and put it in "Prioritized", specify what version bump should happen according to your PR

Add changelog to:
- [x] comit-i comit-network/comit-i#120
- [x] comit-rs comit-network/comit-rs#1222
- [x] bobtimus coblox/bobtimus#110
- [ ] blockchain-contracts coblox/blockchain-contracts#6

Also:
- [x] Fix versioning of comit-i comit-network/comit-i#117

**Comment by thomaseizinger** [comment]
Done in #34.
